services:
  celestedle-api:
    build: .
    env_file: .env
    container_name: ${CONTAINER_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_NAME}.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.${TRAEFIK_NAME}.entrypoints=web"
      - "traefik.http.services.${TRAEFIK_NAME}.loadbalancer.server.port=${PORT}"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
