name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    environment: celestedleEnv
    steps:
      - uses: actions/checkout@v4

      - name: Check Docker installation
        run: command -v docker

      - name: Setup .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" > .env
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "API_URL=https://celestedle-api.mizkyosia.fr/" >> .env

      - name: Build and Vectorize Containers
        run: docker compose up --build -d